version: "3"
services:

  portainer:
      image: portainer/portainer
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 4000:9000
      deploy:
        #mode: replicated
        #replicas: 2
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.role == manager]

  visualizer:
      image: dockersamples/visualizer
      ports:
        - 7070:8080
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      deploy:
        #mode: replicated
        #replicas: 2
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.role == manager]