---
spring:
  profiles:
    active: dev
demo:
  alarm:
    alarmResource: http://10.0.15.21:4040/alarm
  temp:
    tempResource: http://10.0.15.22:5050/temperature
logging:
  level:
    org.springframework.security: DEBUG

security:
  basic:
    enabled: false
  oauth2:
    client:
        access-token-uri: http://10.0.15.11:5000/oauth/token
        user-authorization-uri: http://10.0.15.11:5000/oauth/authorize
auth:
  server:
    url: http://10.0.15.11:5000/oauth/check_token
    clientId: my-trusted-client
    clientsecret: secret

